export const productus = [
  {
    associatedItems: [],
    bundled: "false",
    discount: "0.00",
    ecartapiUrl: "https://eshop-deve.herokuapp.com/api/v2/products/null",
    fulfillment: { quantity: "1", service: "manual", status: null },
    id: "9844781449356",
    imageUrl: null,
    name: "algo",
    price: "10.00",
    productId: null,
    quantity: "1",
    requiresShipping: "true",
    sku: null,
    tax: null,
    taxable: "false",
    variantId: null,
    vendor: null,
    weight: null,
  },
];
